### PR TITLE
Add missing parameter and type definition for transfer

### PR DESCRIPTION
**Pull request by gabrielecirulli**
In my PR #7 I forgot two things:
* Adding the `transfer` parameter to both calls of `postMessage`
* Adding the `transfer` parameter to the definition of the method `send`

This PR corrects that.

### CODE REVIEW

**Review by johnny-quesada-developer — APPROVED** [review]
Great catch! I'll merge it, thanks.

Once I finish merging this, I'll immediately merge another branch where I addressed a similar situation. There were a couple of internal callbacks that weren't sending the transfer parameter. But after this merge, the worker message methods will allow you to transfer data at will.

Also, worker messages now have additional subscriptions:

onResolve, onReject, onCancel, onProgress, onFinalize.

These subscriptions will now enable you, if necessary, to track the lifecycle of a message inside the worker. Before, we only had onCancel. Now, all subscriptions also return a function that can be used to unsubscribe from the listener.

image

**Comment by johnny-quesada-developer** [comment]
Hi @gabrielecirulli, version 6.0.2 is now available.

Thank you so much for your contributions! They are truly valuable, and I'm delighted that you found my humble work useful.

Please don't hesitate to let me know if there's anything else I can assist with. I also warmly invite you to take a look at other packages I've developed.

Again, thank you so much.

**Comment by gabrielecirulli** [comment]
Thank you! This library is great, two way fully-typed communication with a worker is a godsend. It's the only one I could find online that does it, I'm surprised it's not more popular.

**Comment by gabrielecirulli** [comment]
By the way, I'm not sure why but the default version of this library on npm is still 1.0.0 instead of 6.0.0. Might be worth looking into.

**Pull request merged**
